### ISSUE TITLE
Catchment Polygons?

### ISSUE THREAD

**Issue by TLDuhamel** [ESR-NZ/covid_in_wastewater#2]
The dashboard shows the catchment polygons. Are these polygons able to be shared in this repository, or are they already available elsewhere?

<img width="415" alt="image" src="https://user-images.githubusercontent.com/2009756/180721962-ab84e0a0-43e9-440b-a52d-563a68bbe568.png">

**Comment by neon-ninja** [comment]
@TLDuhamel I reached out to @ricdea over email and he said this:

> Re the catchments, it's tricky. They're owned by the individual wastewater providers - lots of regional councils who all seem to have different GIS platforms and a heap of various rules about what we can use the data for. Some providers have restricted what we can do with the maps so we're not able to share the shapefile via github.
> 
> We may still be able to share but it depends on what you want to do with the data. If its for covid modelling or research we can look in to an NDA allowing you access to the maps. We'd just need reassurances about your use cases, storage and retention policies.
> 
> If you just want to map out some of the major areas then many councils have their maps available via arcgis online apis.
> 
> Happy to discuss further, it's been quite a mission! Would love to know more about what you want to do with the maps.

**Comment by TLDuhamel** [comment]
Thanks both, appreciate the response and the challenges faced. Nice work bringing it all together. Bring on centralisation! ;)

I was interested in trying out some different map visualisations of the data, simply for my own practice and interest. Specifically I was going to try choropleth symbology on the catchment polygons, instead of categorised point symbols at test sites. In Auckland for example this might make for a more meaningful map, rather than the cluster of testing points in Mangere.

I haven't found Watercare's catchments on their open data portal, but I'll have a look on other regions' council data portals.

**Comment by neon-ninja** [comment]
See https://www.watercare.co.nz/Water-and-wastewater/Building-and-developing/GIS-maps

**Comment by hel-morris** [comment]
> The dashboard shows the catchment polygons. Are these polygons able to be shared in this repository, or are they already available elsewhere?
> 
> <img alt="image" width="415" src="https://user-images.githubusercontent.com/2009756/180721962-ab84e0a0-43e9-440b-a52d-563a68bbe568.png">

Kia ora,

Sorry for the slow response! neon-ninja is right a lot of the catchment map data was sourced from councils and/or wastewater treatment providers, however again as linked above there are a lot of maps that are publicly available. I compiled a list below if you are still interested! 

[Auckland watercare](https://data-watercare.opendata.arcgis.com/search?collection=Dataset ) 
[Canterbury Regional council ](https://opendata.canterburymaps.govt.nz/maps/canterbury-three-waters-data/about )
[Gisborne district council ](https://geoportal-gizzy.opendata.arcgis.com/)
[Whakatane district council](https://opendata-whakatane.hub.arcgis.com/) 
[Palmerston North City Council](https://data-pncc.opendata.arcgis.com/search?tags=3%20Waters) 
[Rangitikei district council](https://geohub-rangitikeidc.opendata.arcgis.com/search?tags=utilities%2Cinfrastructure%2Cwaste%20water%2Cwater%20supply%2Cstorm%20water%2Cthree%20waters)
[Tararua district council](https://data-tararua.opendata.arcgis.com/datasets/ed85ff60409144bf8b83276bf2c7dda7_0)
[Whanganui district council](https://data.whanganui.govt.nz/search/?limit=100&offset=0&category__identifier__in=utilitiesCommunication)
[Far North district council](https://opendata-fndc.hub.arcgis.com/search?tags=3waters%2Cstorm%20water%2Cwaste%20water%2Cwater%20supply)
[Queenstown Lakes District Council](https://gis-qldc.hub.arcgis.com/)
[New Plymouth district council](https://geohub.npdc.govt.nz/datasets/04b822afbf44460793dea172c3b99e00_6/explore?location=-39.073022%2C174.169050%2C10.63)
[Hamilton City Council](https://data-waikatolass.opendata.arcgis.com/datasets/ea97c3f9f55b4e128fcb9d77eca63095_0/explore?location=-37.769938%2C175.272377%2C13.00)
[Hauraki district council](https://data-waikatolass.opendata.arcgis.com/datasets/d569a90bf96f4fb48914cf49805d4a58_0/explore?location=-37.284693%2C175.729378%2C10.70)
[South waikato district council](https://data-waikatolass.opendata.arcgis.com/datasets/26d96d2ac81b4b489e2816aca80946bf_1)
[Taupo district council](https://data-waikatolass.opendata.arcgis.com/datasets/ce0576b95dda4974b988816ba8e37822_0/explore?location=-38.704041%2C176.155345%2C12.09)
[Waikato district council](https://data-waikatolass.opendata.arcgis.com/maps/e325f85ace5c439188de93d1d1b04585/about)
[Waipa district council](https://data-waikatolass.opendata.arcgis.com/datasets/bde3cfe4409c4cb5b08149bf7aa21008_0/explore?location=-37.966704%2C175.384562%2C11.99)
[Wellington city council](https://data-waikatolass.opendata.arcgis.com/datasets/bde3cfe4409c4cb5b08149bf7aa21008_0/explore?location=-37.966704%2C175.384562%2C11.99)

Thanks for the interest
