### ISSUE TITLE
Commit 6fb3ee4a5bb383d3045c26c4dc87859f6c60e157 removed all data from data csvs?

### ISSUE THREAD

**Issue by kyhwana** [ESR-NZ/covid_in_wastewater#3]
Looks like the commit https://github.com/ESR-NZ/covid_in_wastewater/commit/6fb3ee4a5bb383d3045c26c4dc87859f6c60e157 just removed all the data from all the csv's in /data/ ?
Was this intentional or a mistake?

**Comment by hel-morris** [comment]
> Looks like the commit [6fb3ee4](https://github.com/ESR-NZ/covid_in_wastewater/commit/6fb3ee4a5bb383d3045c26c4dc87859f6c60e157) just removed all the data from all the csv's in /data/ ? Was this intentional or a mistake?

Hi sorry, your correct. Should be updated properly now, thank you!
